services:
  weather-bot:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: weather_bot
    restart: unless-stopped
    volumes:
      - ./app/bot/storage/bd:/app/bot/storage/bd
      - ./app/bot/logger/logs:/app/bot/logger/logs
      - ./app/bot/storage/cache:/app/bot/storage/cache
      - ./app/bot/config:/app/bot/config
    env_file:
      - ./app/bot/config/env/api.env
    environment:
      - TZ=Europe/Moscow
    dns:
      - 8.8.8.8
      - 1.1.1.1
