# Локальные ключи AccuWeather для городов
# Эти ключи генерируются через скрипт fetch.go в папке .adhoc
# Формат:
# city: "LocationKey" (уникальный для каждого города)


# Как получить ключи:
# 1. Убедитесь что у вас есть основной API ключ
# 2. Запустите скрипт из папки .adhoc:
#    go run fetch.go
# 3. Скрипт сгенерирует актуальные LocationKey для указанных городов

Большой Камень: "000000"
Владивосток: "111111"
Екатеринбург: "222222"
Москва: "333333"
Санкт-Петербург: "444444"
